#!/usr/bin/env python3
"""Build pipeline: data/resources.yaml -> README.md + site/data.js

Single source of truth is data/resources.yaml. Never hand-edit the outputs.

Usage:
    python3 scripts/build.py

Requires: pyyaml  (pip install pyyaml)
"""
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.exit("Missing dep: pip install pyyaml")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(ROOT, "data", "resources.yaml")
README_FILE = os.path.join(ROOT, "README.md")
SITE_DATA_FILE = os.path.join(ROOT, "site", "data.js")

SOURCE_LABEL = {"official": "官方", "community": "社区", "vendor": "厂商"}

with open(DATA_FILE, encoding="utf-8") as f:
    doc = yaml.safe_load(f)

categories = doc["categories"]
meta = doc["meta"]

# ---------- 1) site/data.js ----------
site = {"meta": {"updated": str(meta["updated"])}, "categories": []}
for cat in categories:
    entries = []
    for e in cat["entries"]:
        entries.append({
            "name": e["name"],
            "url": e["url"],
            "source": e["source"],
            "platform": e.get("platform", ""),
            "subcat": e.get("subcat", ""),
            "note": e["note"],
            "stars": e.get("stars"),
            "installs": e.get("installs"),
            "verified": str(e.get("last_verified", "")),
            "vmethod": e.get("vmethod", ""),
        })
    site["categories"].append({
        "id": cat["id"], "name": cat["name"], "desc": cat["desc"], "entries": entries,
    })

js = "// GENERATED by scripts/build.py from data/resources.yaml — do not edit by hand\n"
js += "const DATA = " + json.dumps(site, ensure_ascii=False, indent=2) + ";\n"
with open(SITE_DATA_FILE, "w", encoding="utf-8") as f:
    f.write(js)

# ---------- 2) README.md ----------
def fmt(n):
    if n is None:
        return "-"
    if n >= 1000:
        v = n / 1000
        return f"{v:.1f}".rstrip("0").rstrip(".") + "k"
    return str(n)

asset_count = sum(len(c["entries"]) for c in categories if c["id"] != "platforms")
platform_count = sum(len(c["entries"]) for c in categories if c["id"] == "platforms")

lines = []
lines.append("# Awesome Agent Ecosystem [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)")
lines.append("")
lines.append("<!-- GENERATED by scripts/build.py from data/resources.yaml — 请改 YAML，不要直接改本文件 -->")
lines.append("")
lines.append("> 策展 AI Agent 生态的**具体资产**：一个个 skill、MCP server、插件、CLI、规范模板、prompt 库。")
lines.append(f"> 每条记录分发平台与来源属性（官方/厂商/社区）。数据截至 {meta['updated']}。")
lines.append(f"> 具体资产 {asset_count} 条 · 分发平台 {platform_count} 个（平台单列，仅作发现渠道）。")
lines.append("")
lines.append("## 收录标准")
lines.append("")
lines.append("- **热度**：GitHub ★1k+，或细分领域内公认的标杆（可放宽）")
lines.append("- **活跃**：近 6 个月内有实质性更新")
lines.append("- **质量**：文档完整、有真实采用案例、安装量/下载量可验证者优先")
lines.append("- **分层**：标注 `[官方]`（协议/厂商/基金会维护）、`[厂商]` 或 `[社区]`")
lines.append("")
lines.append("## 目录")
lines.append("")
for cat in categories:
    # GitHub 锚点规则：小写、去括号与斜杠、空格转连字符（CJK 保留）
    anchor = re.sub(r"[（）()/.,]", "", cat["name"].lower()).replace(" ", "-")
    lines.append(f"- [{cat['name']}](#{anchor})")
lines.append("")
lines.append("---")
lines.append("")

for cat in categories:
    lines.append(f"## {cat['name']}")
    lines.append("")
    lines.append(f"> {cat['desc']}")
    lines.append("")
    lines.append("| 资产 | 子类 | 来源 | 平台 | 热度 | 点评 |")
    lines.append("|---|---|---|---|---|---|")
    for e in cat["entries"]:
        src = SOURCE_LABEL.get(e["source"], e["source"])
        metrics = []
        if e.get("stars"):
            metrics.append(f"★{fmt(e['stars'])}")
        if e.get("installs"):
            metrics.append(f"安装 {fmt(e['installs'])}")
        heat = " / ".join(metrics) if metrics else "-"
        subcat = e.get("subcat") or "-"
        lines.append(f"| [{e['name']}]({e['url']}) | {subcat} | {src} | {e.get('platform','-')} | {heat} | {e['note']} |")
    lines.append("")

lines.append("## 贡献")
lines.append("")
lines.append("见 [CONTRIBUTING.md](CONTRIBUTING.md)。所有条目改动请编辑 `data/resources.yaml` 后运行 `python3 scripts/build.py`。")
lines.append("")
lines.append("## License")
lines.append("")
lines.append("[CC0-1.0](LICENSE)")
lines.append("")

with open(README_FILE, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print(f"OK  site/data.js      ({sum(len(c['entries']) for c in categories)} entries)")
print(f"OK  README.md         ({asset_count} assets + {platform_count} platforms)")
