#!/usr/bin/env python3
"""Build public catalog views from the three validated v3 source files."""
import argparse
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]


def build_outputs(root=ROOT):
    root = Path(root)
    # Validate before constructing or writing any generated output.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from validate import validate_catalog

    errors = validate_catalog(root)
    if errors:
        raise ValueError("\n".join(errors))

    categories_doc = yaml.safe_load((root / "data" / "categories.yaml").read_text(encoding="utf-8"))
    sources_doc = yaml.safe_load((root / "data" / "sources.yaml").read_text(encoding="utf-8"))
    resources_doc = yaml.safe_load((root / "data" / "resources.yaml").read_text(encoding="utf-8"))
    categories = categories_doc["categories"]
    resources = resources_doc["resources"]
    meta = resources_doc["meta"]

    catalog = {
        "schema_version": 3,
        "categories": categories_doc,
        "sources": sources_doc,
        "resources": resources_doc,
    }
    site_data = {
        "meta": {
            "updated": str(meta["updated"]),
            "catalogVersion": meta["catalog_version"],
            "review": meta["review"],
        },
        "categories": [],
    }
    for category in categories:
        entries = []
        for resource in resources:
            classification = resource["classification"]
            if classification["category"] != category["id"]:
                continue
            provenance = resource["provenance"]
            upstream = provenance["upstream"]
            entries.append({
                "id": resource["id"],
                "name": resource["title"],
                "url": upstream["url"],
                "source": provenance["relation"],
                "relation": provenance["relation"],
                "platform": ", ".join(channel.get("kind", "") for channel in resource["distribution"]),
                "subcat": classification["subtype"] or "",
                "note": resource["summary"],
                "stars": None,
                "installs": None,
                "verified": resource["verification"].get("checked_at") or "",
                "vmethod": "",
                "purpose": resource["purpose"],
                "classification": classification,
                "provenance": provenance,
                "license": resource["license"],
                "distribution": resource["distribution"],
                "previews": resource["previews"],
                "compatibility": resource["compatibility"],
                "components": resource["components"],
                "lifecycle": resource["lifecycle"],
                "review": resource["review"],
                "verification": resource["verification"],
                "authors": resource["authors"],
                "publisher": resource["publisher"],
            })
        site_data["categories"].append({
            "id": category["id"],
            "name": category["label"],
            "desc": category["definition"],
            "entries": entries,
        })

    js = "// GENERATED by scripts/build.py from schema v3 sources — do not edit by hand\n"
    js += "const DATA = " + json.dumps(site_data, ensure_ascii=False, indent=2) + ";\n"
    catalog_json = json.dumps(catalog, ensure_ascii=False, indent=2) + "\n"

    lines = [
        "# Awesome Agent Ecosystem [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)",
        "",
        "<!-- GENERATED by scripts/build.py from data/categories.yaml, data/sources.yaml and data/resources.yaml -->",
        "",
        f"> Public asset catalog `{meta['catalog_version']}` · review: **{meta['review']['status']}** · updated {meta['updated']}.",
        "> This is a draft directory. A pending review or source inspection does not claim runtime compatibility.",
        "",
        "## Categories",
        "",
    ]
    for category in categories:
        lines.append(f"- [{category['label']}](#{category['id']})")
    lines += ["", "## Resources", ""]
    for category in categories:
        items = [r for r in resources if r["classification"]["category"] == category["id"]]
        lines += [f'<a id="{category["id"]}"></a>', f"### {category['label']}", "", f"> {category['definition']}", ""]
        if not items:
            lines += ["No resources yet.", ""]
            continue
        lines += ["| Resource | Subtype | Relation | Lifecycle | Verification | License |", "|---|---|---|---|---|---|"]
        for resource in items:
            classification = resource["classification"]
            subtype = classification.get("subtype") or "—"
            life = resource["lifecycle"]["state"]
            verification = resource["verification"]["level"]
            license_status = resource["license"]["status"]
            url = resource["provenance"]["upstream"]["url"]
            lines.append(f"| [{resource['title']}]({url}) (`{resource['id']}`) | {subtype} | {resource['provenance']['relation']} | {life} | {verification} | {license_status} |")
        lines.append("")
        if category["id"] == "plugins":
            for resource in items:
                if not resource["components"]:
                    continue
                lines += ["", f"**Components in {resource['title']}**", "",
                          "| Component ID | Type | Delivery | Resource reference |", "|---|---|---|---|"]
                for component in resource["components"]:
                    resource_ref = component.get("resource_id") or "—"
                    lines.append(f"| `{component['id']}` | `{component['type']}` | `{component['delivery']}` | `{resource_ref}` |")
                lines.append("")
    lines += ["## Sources", "", "Source roles and update scopes are recorded in `data/sources.yaml`.", ""]

    outputs = {
        root / "README.md": "\n".join(lines),
        root / "site" / "data.js": js,
        root / "site" / "catalog.json": catalog_json,
    }
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return len(resources)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT, help="catalog root (defaults to this repository)")
    args = parser.parse_args()
    try:
        count = build_outputs(args.root)
    except ValueError as exc:
        print(f"FAIL: catalog validation failed\n{exc}", file=sys.stderr)
        return 1
    print(f"OK  README.md, site/data.js and site/catalog.json ({count} resources)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
